on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'brokehfyks_4'
          server: '196.40.97.175'
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local_path: './static/*'
          remote_path: '/usr/www/users/brokehfyks/dev.brokenpony.club/github-test'
          args: '-o ConnectTimeout=5'
